/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {
ArrayList <Gerente> listaEmpleados = new ArrayList();
ArrayList <Mensajes> listaMensajes = new ArrayList();
int contG = 0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_listarDirectorio = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jb_enviarya = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textA = new javax.swing.JTextArea();
        one = new javax.swing.JTextField();
        two = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jb_enviarBrodcast = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInbox = new javax.swing.JTable();

        jLabel28.setText("To:");

        jLabel29.setText("From:");

        jb_enviarya.setText("Enviar");
        jb_enviarya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_enviaryaMouseClicked(evt);
            }
        });

        textA.setColumns(20);
        textA.setRows(5);
        jScrollPane1.setViewportView(textA);

        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_listarDirectorioLayout = new javax.swing.GroupLayout(jd_listarDirectorio.getContentPane());
        jd_listarDirectorio.getContentPane().setLayout(jd_listarDirectorioLayout);
        jd_listarDirectorioLayout.setHorizontalGroup(
            jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarDirectorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_enviarya)
                .addGap(57, 57, 57))
            .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                .addGroup(jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two))))
                    .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jd_listarDirectorioLayout.setVerticalGroup(
            jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_listarDirectorioLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(one)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_listarDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarDirectorioLayout.createSequentialGroup()
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jb_enviarya)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Gerente General");

        jLabel2.setText("Gerente de Area");

        jLabel3.setText("Empleados");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Agregar Empleado");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gerente", "GerenteGeneral", "Empleado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("Cambiar Puesto");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jb_enviarBrodcast.setText("Enviar Bodcast");
        jb_enviarBrodcast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_enviarBrodcastMouseClicked(evt);
            }
        });

        jButton6.setText("Enviar Mensaje Personal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jb_enviarBrodcast)
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jb_enviarBrodcast)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla Empleado", jPanel2);

        tablaInbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Para", "De", "Mensaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaInbox);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver mensajes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        /*
        private String nombre;
    private String idEmpresa;
    private String contrasena;
    private String salario;
    private String puesto;
        */
        if (contG<1) {
            String nombre = jTextField1.getText();
            String idEmpresa = JOptionPane.showInputDialog(this, "Ingrese idEmpresa: ");
            String contrasena = JOptionPane.showInputDialog(this, "Ingrese contrasena: ");
            String salario = JOptionPane.showInputDialog(this, "Ingrese salario: ");
            String puesto = JOptionPane.showInputDialog(this, "Ingrese puesto: ");
        
            listaEmpleados.add(new Gerente(nombre, idEmpresa, contrasena, salario, "Gerencia"));
            contG++;
        }else
            JOptionPane.showMessageDialog(this, "Solo puede haber un gerente general.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (listaEmpleados.size()>0) {
            String nombre = jTextField2.getText();
            String idEmpresa = JOptionPane.showInputDialog(this, "Ingrese idEmpresa: ");
            String contrasena = JOptionPane.showInputDialog(this, "Ingrese contrasena: ");
            String salario = JOptionPane.showInputDialog(this, "Ingrese salario: ");
            String puesto = JOptionPane.showInputDialog(this, "Ingrese puesto: ");
            
            
            EmpleadosArea x = (EmpleadosArea) new EmpleadosArea(nombre, idEmpresa, contrasena, salario, puesto, (Gerente) listaEmpleados.get(0));
            ((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().add(x);
            
            DefaultComboBoxModel m = (DefaultComboBoxModel) jComboBox1.getModel();
            m.addElement(x);
            jComboBox1.setModel(m);
            jTextField2.setText("");
        }else
            JOptionPane.showMessageDialog(this, "No ha agregado gerente general.");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        if (listaEmpleados.size()>0) {
            EmpleadosP temp;
            String nombre = jTextField3.getText();
            String idEmpresa = JOptionPane.showInputDialog(this, "Ingrese idEmpresa: ");
            String contrasena = JOptionPane.showInputDialog(this, "Ingrese contrasena: ");
            String salario = JOptionPane.showInputDialog(this, "Ingrese salario: ");
            String puesto = JOptionPane.showInputDialog(this, "Ingrese puesto: ");
            int pos = -1;
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) jComboBox1.getModel();
            if (modelo.getSelectedItem() instanceof EmpleadosArea) {
                //ver a que gerente de area se le va asignar este empleado.
                for (int i = 0; i < listaEmpleados.get(0).getListaEmpleadosArea().size(); i++) {
                    if (listaEmpleados.get(0).getListaEmpleadosArea().get(i) == jComboBox1.getSelectedItem()) {
                        pos = i;
                    }
                }
                EmpleadosArea jefe = ((Gerente) listaEmpleados.get(0)).getListaEmpleadosArea().get(pos);
                temp = new EmpleadosP(nombre, idEmpresa, contrasena, salario, puesto, jefe);
                listaEmpleados.get(0).getListaEmpleadosArea().get(pos).getListaEmpleadosP().add(temp);
               
            }
        }else
            JOptionPane.showMessageDialog(this, "Asegurese de tener un gerente general \n"
                    + "y de tener un Gerente de Area a quien asignarle su empleado\n");
        /*
        agrego empleado.. pero va ser gerenteArea o empleado normal???
        */
    }//GEN-LAST:event_jButton3MouseClicked

    /*public void listar_no_orden(Object empleado, DefaultMutableTreeNode nodo) {
        try {
            
            for (EmpleadosArea temp : ((Gerente)empleado).getListaEmpleadosArea()) {
                if (temp.getListaEmpleadosP().isEmpty()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                    listar_no_orden(temp, n);
                }
            }
            /*if (empleado instanceof Gerente) {
                for (EmpleadosArea p : ((Gerente) empleado).getListaEmpleadosArea() ) {
                    
                    if (p.getListaEmpleadosP().isEmpty()) {
                        DefaultMutableTreeNode n = new DefaultMutableTreeNode(p);
                        nodo.add(n);
                    } else {
                        DefaultMutableTreeNode n = new DefaultMutableTreeNode(p);
                        nodo.add(n);
                        listar_no_orden(p, n);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "hola else");
                for (EmpleadosArea p2 : ((EmpleadosArea)empleado).getListaEmpleadosP()) {
                    JOptionPane.showMessageDialog(this, "hola");
                    if (p2.getListaEmpleadosP().isEmpty()) {
                        DefaultMutableTreeNode n = new DefaultMutableTreeNode(p2);
                        nodo.add(n);
                        JOptionPane.showMessageDialog(this, "hola1");
                    } else {
                        DefaultMutableTreeNode n = new DefaultMutableTreeNode(p2);
                        nodo.add(n);
                        listar_no_orden(p2, n);
                        JOptionPane.showMessageDialog(this, "hola2");
                    }
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
*/    
    
   
    
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 1) {
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gerente", "GerenteGeneral", "Empleado"
            }
        ));
            
            if (listaEmpleados.size() > 0) {
              DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
              String row [] = new String [3];
              
              row[0]=((Gerente)listaEmpleados.get(0)).toString();
              
                for (int i = 0; i < ((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().size(); i++) {
                    row[1]= ((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().get(i).toString();
                    if (((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().get(i).getListaEmpleadosP().size() >=0) {
                        for (int j = 0; j < ((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().get(i).getListaEmpleadosP().size(); j++) {
                            row[2]= ((Gerente)listaEmpleados.get(0)).getListaEmpleadosArea().get(i).getListaEmpleadosP().get(j).toString();
                            m.addRow(row);
                        }
                    }else{
                        row[3]="Sin empleados";
                        m.addRow(row);
                    }
                }
              jTable1.setModel(m);
                
            }
        }
        
        
        if (jTabbedPane1.getSelectedIndex() == 2) {
            
            tablaInbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Para", "De", "Mensaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
            
            for (Mensajes t : listaMensajes ) {
                Object row4 [] = {t.getDestino(),t.getFuente(),t.getCuerpo()};
                  DefaultTableModel m2 = (DefaultTableModel) tablaInbox.getModel();
                m2.addRow(row4);
                tablaInbox.setModel(m2);  
                
            }
            
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jTable1.getSelectedRow();
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jb_enviarBrodcastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_enviarBrodcastMouseClicked
        // TODO add your handling code here:
       jd_listarDirectorio.setVisible(true);
       
    }//GEN-LAST:event_jb_enviarBrodcastMouseClicked

    private void jb_enviaryaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_enviaryaMouseClicked
        // TODO add your handling code here:
        String to = one.getText();
        String from = two.getText();
        String cuerpo = textA.getText();
        Mensajes mensaje = new Mensajes(to, cuerpo, false, false, cuerpo);
        listaMensajes.add(mensaje);
        adminMensajes am = new adminMensajes("./mensajes.sc");
        am.cargarArchivo();
        am.setMensaje(mensaje);
        am.escribirArchivo();
    }//GEN-LAST:event_jb_enviaryaMouseClicked

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jb_enviarBrodcast;
    private javax.swing.JButton jb_enviarya;
    private javax.swing.JDialog jd_listarDirectorio;
    private javax.swing.JTextField one;
    private javax.swing.JTable tablaInbox;
    private javax.swing.JTextArea textA;
    private javax.swing.JTextField two;
    // End of variables declaration//GEN-END:variables
}
